package sshconfig

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/kerren/op-ssh-manager/internal/model"
	"github.com/kerren/op-ssh-manager/internal/platform"
)

const (
	// HeaderTemplate is the header comment for generated config
	HeaderTemplate = `# SSH Configuration - Managed by op-ssh-manager
# Generated: %s
# Hosts: %d
# Content Hash: %s
#
# DO NOT EDIT THIS FILE DIRECTLY
# Changes will be overwritten on next sync
# To modify settings, update the corresponding items in 1Password
#
`
)

// GeneratorConfig holds configuration for the SSH config generator
type GeneratorConfig struct {
	// IdentityAgent is the path to the 1Password SSH agent socket
	IdentityAgent string

	// IdentitiesOnly forces SSH to only use specified identities
	IdentitiesOnly bool

	// AddComments adds explanatory comments to the config
	AddComments bool

	// UserEmail is the current user's email for per-user mappings
	UserEmail string
}

// DefaultGeneratorConfig returns the default generator configuration
func DefaultGeneratorConfig() *GeneratorConfig {
	return &GeneratorConfig{
		IdentityAgent:  platform.GetIdentityAgent(),
		IdentitiesOnly: true,
		AddComments:    true,
	}
}

// Generator generates SSH config from inventory
type Generator struct {
	Config *GeneratorConfig
}

// NewGenerator creates a new SSH config generator
func NewGenerator(cfg *GeneratorConfig) *Generator {
	if cfg == nil {
		cfg = DefaultGeneratorConfig()
	}
	return &Generator{Config: cfg}
}

// GenerateResult contains the result of config generation
type GenerateResult struct {
	Content     []byte
	Hash        string
	HostCount   int
	GeneratedAt time.Time
}

// Generate generates the SSH config from an inventory
func (g *Generator) Generate(inv *model.Inventory) (*GenerateResult, error) {
	var buf bytes.Buffer
	now := time.Now()

	// Get sorted list of server aliases for deterministic output
	aliases := make([]string, 0, len(inv.Servers))
	for alias := range inv.Servers {
		aliases = append(aliases, alias)
	}
	sort.Strings(aliases)

	// Generate config for each server
	for _, alias := range aliases {
		server := inv.Servers[alias]
		g.generateHostBlock(&buf, server, inv)
		buf.WriteString("\n")
	}

	content := buf.Bytes()
	hash := sha256.Sum256(content)
	hashStr := hex.EncodeToString(hash[:8]) // Short hash for display

	// Prepend header
	header := fmt.Sprintf(HeaderTemplate, now.Format(time.RFC3339), len(aliases), hashStr)
	fullContent := append([]byte(header), content...)

	return &GenerateResult{
		Content:     fullContent,
		Hash:        hashStr,
		HostCount:   len(aliases),
		GeneratedAt: now,
	}, nil
}

// generateHostBlock generates the config block for a single host
func (g *Generator) generateHostBlock(buf *bytes.Buffer, server *model.ServerRecord, inv *model.Inventory) {
	// Add comment with server info if enabled
	if g.Config.AddComments {
		if server.Environment != "" || server.OwnerTeam != "" {
			buf.WriteString("# ")
			if server.Environment != "" {
				buf.WriteString(fmt.Sprintf("Env: %s", server.Environment))
			}
			if server.OwnerTeam != "" {
				if server.Environment != "" {
					buf.WriteString(" | ")
				}
				buf.WriteString(fmt.Sprintf("Team: %s", server.OwnerTeam))
			}
			buf.WriteString("\n")
		}
	}

	// Host alias
	buf.WriteString(fmt.Sprintf("Host %s\n", server.Alias))

	// HostName
	buf.WriteString(fmt.Sprintf("    HostName %s\n", server.Hostname))

	// Port (only if non-default)
	if server.Port != 22 {
		buf.WriteString(fmt.Sprintf("    Port %d\n", server.Port))
	}

	// User (determine based on current user's email or default)
	user := g.determineUser(server)
	if user != "" {
		buf.WriteString(fmt.Sprintf("    User %s\n", user))
	}

	// ProxyJump for jump hosts
	if server.JumpAlias != "" {
		buf.WriteString(fmt.Sprintf("    ProxyJump %s\n", server.JumpAlias))
	}

	// Identity settings for 1Password SSH agent
	if g.Config.IdentitiesOnly {
		buf.WriteString("    IdentitiesOnly yes\n")
	}

	if g.Config.IdentityAgent != "" {
		buf.WriteString(fmt.Sprintf("    IdentityAgent %s\n", g.Config.IdentityAgent))
	}

	// IdentityFile for public keys
	keys := g.determineKeys(server, inv)
	for _, key := range keys {
		if key.LocalPath != "" {
			buf.WriteString(fmt.Sprintf("    IdentityFile %s\n", key.LocalPath))
		}
	}
}

// determineUser determines the appropriate user for a server
func (g *Generator) determineUser(server *model.ServerRecord) string {
	// Check for per-user mapping
	if g.Config.UserEmail != "" {
		for _, ua := range server.Users {
			if strings.EqualFold(ua.Email, g.Config.UserEmail) {
				return ua.LinuxUser
			}
		}
	}
	return server.DefaultUser
}

// determineKeys determines the keys to use for a server
func (g *Generator) determineKeys(server *model.ServerRecord, inv *model.Inventory) []*model.ResolvedKey {
	var keys []*model.ResolvedKey

	// Check for per-user key mapping
	if g.Config.UserEmail != "" {
		for _, ua := range server.Users {
			if strings.EqualFold(ua.Email, g.Config.UserEmail) && len(ua.Keys) > 0 {
				// Use user-specific keys
				for _, keyRef := range ua.Keys {
					if resolved, ok := inv.Keys[keyRef.UniqueKey()]; ok {
						keys = append(keys, resolved)
					}
				}
				return keys
			}
		}
	}

	// Use server-level keys
	for _, keyRef := range server.Keys {
		if resolved, ok := inv.Keys[keyRef.UniqueKey()]; ok {
			keys = append(keys, resolved)
		}
	}

	return keys
}

// GenerateMinimal generates a minimal config without comments
func (g *Generator) GenerateMinimal(inv *model.Inventory) ([]byte, error) {
	originalComments := g.Config.AddComments
	g.Config.AddComments = false
	defer func() { g.Config.AddComments = originalComments }()

	result, err := g.Generate(inv)
	if err != nil {
		return nil, err
	}

	// Strip header for minimal output
	lines := strings.Split(string(result.Content), "\n")
	var output []string
	inHeader := true
	for _, line := range lines {
		if inHeader && strings.HasPrefix(line, "#") {
			continue
		}
		inHeader = false
		output = append(output, line)
	}

	return []byte(strings.TrimLeft(strings.Join(output, "\n"), "\n")), nil
}

// ValidateGenerated validates the generated config syntax
// This is a basic validation - for full validation, use `ssh -G`
func ValidateGenerated(content []byte) error {
	lines := strings.Split(string(content), "\n")
	var currentHost string

	for i, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		parts := strings.Fields(line)
		if len(parts) < 2 {
			return fmt.Errorf("line %d: invalid directive (no value): %s", i+1, line)
		}

		directive := strings.ToLower(parts[0])

		switch directive {
		case "host":
			currentHost = parts[1]
		case "hostname", "port", "user", "identityfile", "identityagent",
			"identitiesonly", "proxyjump", "proxycommand", "localforward",
			"remoteforward", "dynamicforward", "addkeystoagent",
			"forwardagent", "serveraliveinterval", "serveralivecountmax",
			"stricthostkeychecking", "userknownhostsfile", "loglevel":
			// Valid directives
			if currentHost == "" && directive != "host" {
				return fmt.Errorf("line %d: directive '%s' outside of Host block", i+1, directive)
			}
		default:
			// Unknown directive - warn but don't fail
		}
	}

	return nil
}
