package reporting

import (
	"fmt"
	"html/template"
	"io"
	"os"
	"strings"
)

const htmlTemplate = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SSH Inventory Report</title>
    <style>
        * {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            line-height: 1.6;
            color: #333;
            padding: 20px;
            max-width: 1400px;
            margin: 0 auto;
        }
        h1 {
            color: #1a1a2e;
            margin-bottom: 10px;
        }
        .metadata {
            background: #f5f5f5;
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 20px;
        }
        .metadata p {
            margin: 5px 0;
        }
        .metadata strong {
            color: #555;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            font-size: 14px;
        }
        th, td {
            padding: 12px 8px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background: #1a1a2e;
            color: white;
            font-weight: 600;
            position: sticky;
            top: 0;
        }
        tr:hover {
            background: #f8f8f8;
        }
        tr:nth-child(even) {
            background: #fafafa;
        }
        tr:nth-child(even):hover {
            background: #f0f0f0;
        }
        .tag {
            display: inline-block;
            background: #e0e0e0;
            padding: 2px 8px;
            border-radius: 12px;
            font-size: 12px;
            margin: 1px;
        }
        .key-resolved {
            color: #2e7d32;
        }
        .key-missing {
            color: #c62828;
        }
        .jump-path {
            font-family: monospace;
            font-size: 12px;
            color: #666;
        }
        @media print {
            th {
                background: #333 !important;
                -webkit-print-color-adjust: exact;
            }
        }
    </style>
</head>
<body>
    <h1>SSH Inventory Report</h1>

    <div class="metadata">
        <p><strong>Generated:</strong> {{.Metadata.GeneratedAt.Format "2006-01-02 15:04:05 MST"}}</p>
        {{if .Metadata.GeneratedBy}}<p><strong>Generated By:</strong> {{.Metadata.GeneratedBy}}</p>{{end}}
        {{if .Metadata.AccountName}}<p><strong>Account:</strong> {{.Metadata.AccountName}}</p>{{end}}
        <p><strong>Total Servers:</strong> {{.Metadata.TotalServers}}</p>
        <p><strong>Total Keys:</strong> {{.Metadata.TotalKeys}}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Alias</th>
                <th>Hostname</th>
                <th>Port</th>
                <th>User</th>
                <th>Jump Host</th>
                <th>Keys</th>
                <th>Status</th>
                <th>Environment</th>
                <th>Tags</th>
            </tr>
        </thead>
        <tbody>
            {{range .Rows}}
            <tr>
                <td><strong>{{.Alias}}</strong></td>
                <td>{{.Hostname}}</td>
                <td>{{.Port}}</td>
                <td>{{.RemoteUser}}{{if .UserEmail}}<br><small>({{.UserEmail}})</small>{{end}}</td>
                <td>
                    {{if .JumpAlias}}{{.JumpAlias}}{{end}}
                    {{if .JumpPath}}<br><span class="jump-path">{{.JumpPath}}</span>{{end}}
                </td>
                <td>{{range $i, $key := .KeyTitles}}{{if $i}}, {{end}}{{$key}}{{end}}</td>
                <td>
                    <span class="key-resolved">{{.KeysResolved}} resolved</span>
                    {{if gt .KeysMissing 0}}<br><span class="key-missing">{{.KeysMissing}} missing</span>{{end}}
                </td>
                <td>{{.Environment}}</td>
                <td>{{range .Tags}}<span class="tag">{{.}}</span>{{end}}</td>
            </tr>
            {{end}}
        </tbody>
    </table>
</body>
</html>`

// HTMLWriter writes reports in HTML format
type HTMLWriter struct{}

// NewHTMLWriter creates a new HTML writer
func NewHTMLWriter() *HTMLWriter {
	return &HTMLWriter{}
}

// Write writes a report to a writer
func (w *HTMLWriter) Write(report *Report, writer io.Writer) error {
	tmpl, err := template.New("report").Parse(htmlTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	return tmpl.Execute(writer, report)
}

// WriteFile writes a report to a file
func (w *HTMLWriter) WriteFile(report *Report, path string) error {
	file, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("failed to create file: %w", err)
	}
	defer file.Close()

	return w.Write(report, file)
}

// escapeHTML escapes HTML special characters
func escapeHTML(s string) string {
	replacer := strings.NewReplacer(
		"&", "&amp;",
		"<", "&lt;",
		">", "&gt;",
		"\"", "&quot;",
		"'", "&#39;",
	)
	return replacer.Replace(s)
}
